{% set name = "wxdata" %}
{% set version = "1.5" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}""

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wxdata-{{ version }}.tar.gz
  sha256: 7efaca455f6f1cd2362127d91ba910ee19507a46584db16b6e4dfec5fb8363b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - metpy >=1.5.1
    - numpy >=1.24
    - pandas >=2.2
    - xarray >=2023.1.0
    - netcdf4 >=1.7.1
    - shapeography >=1.0
    - beautifulsoup4 >=4.13.4
    - requests >=2.32.4
    - cfgrib >=0.9.10.4
    - dask-core >=2025.5.1
    - tqdm >=4.67.3
    - ecmwf-opendata >=0.3.26
    - openpyxl >=3.1.5

test:
  imports:
    - wxdata
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/edrewitz/WxData
  summary: An open source library for downloading and pre/post-processing various types of weather data. Friendly for VPN/PROXY connections.
  license: MIT
  license_file: LICENSE
  doc_url: https://pypi.org/project/wxdata/
  dev_url: https://github.com/edrewitz/WxData

extra:
  recipe-maintainers:
    - edrewitz
